<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Comment extends Model
{
    public function save(array $options = [])
    {
        sleep(8);
        parent::save($options);
        return true;//parent::save($options); // TODO: Change the autogenerated stub
    }
}
